### ISSUE TITLE
pod "BlurImageProcessor" got a error

### ISSUE THREAD

**Issue by LengBinBin** [danielalves/BlurImageProcessor#4]
i have got this error 

                Undefined symbols for architecture x86_64:
                "_OBJC_CLASS_$_ALDBlurImageProcessor", referenced from:-
                objc-class-ref in SecretAnimationCell.o
                ld: symbol(s) not found for architecture x86_64
                clang: error: linker command failed with exit code 1 (use -v to see invocation)

when i use 

                self.processor = [[ALDBlurImageProcessor alloc] initWithImage: _fuzzyView.image];

 can give some advance for me？

**Comment by danielalves** [comment]
Well, this is a linker error. It means the linker was not able to find `ALDBlurImageProcessor` in the compilation for 64 bits platforms. This should not be a problem since `ALDBlurImageProcessor` works for 32 bits and 64 bits (as you can see running the **Demo app**). So you probably forgot to link `ALDBlurImageProcessor` with your app target. Things to check:

1 - Did you run `pod install` after adding `pod "BlurImageProcessor"` to your **Podfile**? It should set all configurations for you.
2 - Open your compilation target **Build Phases** view and check if `libPods.a` (the library generated by `pod install`) is listed in the **Link Binary With Libraries** section. (You can reach this view by selecting your project in the *Project Navigator* -> Selecting your target -> Selecting the *Build Phases* tab).
3 - In your **Podfile**, check if you are adding `pod "BlurImageProcessor"` for the target you are trying to compile.
4 - If everything is ok, try to clean and build your project.

You'll probably be able to compile with no errors =)

**Comment by danielalves** [comment]
Since the Demo app is compiling for 32 and 64 bits, I'll close this issue.

**Comment by LengBinBin** [comment]
All the item has been done but still Undefined symbols Error whatever the device is iPhone or the iOS simulator .
I use the ALDBlurImageProcessor.h and ALDBlurImageProcessor.m file it works well for now. but i still don't know why the pod got that error. 
Thanks for your replay
